"""
ELEOS — Member 1: Unit & Pipeline Test Suite
Tests:
1. All 9 canonical synthetic sanity checks from Section 42
2. Accounting identity consistency
3. Peer group fallback hierarchy
4. Output JSON schema conformity
5. Age penalty calibration (ensuring age does not disproportionately dominate score)
"""

import sys
import json
import pytest
from pathlib import Path
import pandas as pd
import numpy as np

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

DATA_DIR = ROOT_DIR / "data" / "synthetic"
DATA_DIR = ROOT_DIR / "data" / "reference"
OUTPUTS_DIR = ROOT_DIR / "outputs"


@pytest.fixture(scope="module")
def pipeline_data():
    """Loads all pipeline output data generated by Member 1 pipeline."""
    from scripts.run_member1_pipeline import run_pipeline
    # Run pipeline to ensure fresh artifacts exist
    run_pipeline(num_ngos=200, contamination=0.05)

    df_master = pd.read_csv(DATA_DIR / "ngo_master.csv")
    df_profile = pd.read_csv(DATA_DIR / "ngo_public_profile.csv")
    df_fin_feats = pd.read_csv(DATA_DIR / "financial_features.csv")
    df_op_feats = pd.read_csv(DATA_DIR / "operational_features.csv")
    df_fin_reports = pd.read_csv(DATA_DIR / "financial_reports.csv")

    with open(OUTPUTS_DIR / "ngo_assessments.json", "r", encoding="utf-8") as f:
        assessments = json.load(f)

    return {
        "master": df_master,
        "profile": df_profile,
        "fin_feats": df_fin_feats,
        "op_feats": df_op_feats,
        "fin_reports": df_fin_reports,
        "assessments": {a["ngo_id"]: a for a in assessments}
    }


def test_accounting_identities(pipeline_data):
    """Verifies that 98%+ of synthetic financial statements satisfy strict accounting identities."""
    df_fin = pipeline_data["fin_reports"]
    expense_cols = [
        "programme_expenses", "administrative_expenses", "fundraising_expenses",
        "employee_expenses", "consultancy_expenses", "material_expenses", "other_expenses"
    ]

    reconciled_exp = 0
    reconciled_surplus = 0
    total = len(df_fin)

    for _, row in df_fin.iterrows():
        tot_inc = float(row["total_income"])
        tot_exp = float(row["total_expenditure"])
        surplus = float(row["surplus_or_deficit"])

        items_sum = sum(float(row[c]) for c in expense_cols if not pd.isna(row[c]))
        if abs(tot_exp - items_sum) < 1.0:
            reconciled_exp += 1

        if abs(surplus - (tot_inc - tot_exp)) < 1.0:
            reconciled_surplus += 1

    assert (reconciled_exp / total) >= 0.98, f"Reconciliation rate too low: {reconciled_exp / total}"
    assert (reconciled_surplus / total) >= 0.98, f"Surplus reconciliation rate too low: {reconciled_surplus / total}"


def test_peer_group_fallback_hierarchy(pipeline_data):
    """Verifies peer group fallback behavior when specific groups have < MIN_PEER_GROUP_SIZE."""
    df_fin_feats = pipeline_data["fin_feats"]
    assert "peer_group" in df_fin_feats.columns
    assert "peer_group_fallback_level" in df_fin_feats.columns
    assert "peer_group_size" in df_fin_feats.columns

    # Verify fallback levels are valid
    valid_levels = {"specific", "sector_broad", "national_broad"}
    actual_levels = set(df_fin_feats["peer_group_fallback_level"].unique())
    assert actual_levels.issubset(valid_levels)

    # Verify group sizes are >= 10
    for size in df_fin_feats["peer_group_size"]:
        assert size >= 10, f"Peer group size {size} is less than minimum 10"


def test_sanities_test1_established_ngo(pipeline_data):
    """Sanity Test 1: Complete established NGO has strong evidence, but no artificial 100% score."""
    df_master = pipeline_data["master"]
    assessments = pipeline_data["assessments"]

    # Find mature NGO with >= 5 years age and >= 3 reports
    df_fin = pipeline_data["fin_feats"]
    mature_candidates = df_master[(df_master["ngo_age_years"] >= 10) & (df_master["source_count"] >= 2)]
    found = False
    for nid in mature_candidates["ngo_id"]:
        f_row = df_fin[df_fin["ngo_id"] == nid].iloc[0]
        if f_row["reports_count"] >= 3:
            asmnt = assessments[nid]
            assert asmnt["trustability_score"] >= 65.0, f"Established NGO score too low: {asmnt['trustability_score']}"
            assert asmnt["trustability_score"] <= 98.0, "Score should not be artificially perfect (100%)"
            assert asmnt["data_confidence"] >= 0.70, f"Established NGO confidence too low: {asmnt['data_confidence']}"
            found = True
            break
    assert found, "Could not locate qualifying established NGO candidate"


def test_sanities_test2_new_ngo_no_fraud_flag(pipeline_data):
    """Sanity Test 2: New NGO (< 1 yr old) has limited evidence coverage, but zero fraud accusations."""
    df_master = pipeline_data["master"]
    assessments = pipeline_data["assessments"]

    young_ngos = df_master[df_master["ngo_age_years"] < 1.0]
    assert len(young_ngos) > 0, "No new NGOs generated in synthetic population"

    for nid in young_ngos["ngo_id"]:
        asmnt = assessments[nid]
        # Should NOT be labelled high risk solely due to being new
        assert asmnt["score_interpretation"]["label"] in ["Limited Evidence Coverage", "Insufficient Evidence", "Moderate Evidence Coverage"], \
            f"Young NGO got improper harsh label: {asmnt['score_interpretation']['label']}"
        # Negative evidence must not contain moral or fraud assertions
        for neg in asmnt["negative_evidence"]:
            assert "fraud" not in neg.lower()
            assert "dishonest" not in neg.lower()
            assert "untrustworthy" not in neg.lower()


def test_sanities_test3_small_ngo_not_penalized(pipeline_data):
    """Sanity Test 3: Small NGO with clean disclosures achieves moderate-to-strong evidence coverage."""
    df_fin = pipeline_data["fin_feats"]
    assessments = pipeline_data["assessments"]

    small_ngos = df_fin[(df_fin["income_scale"] == "Small") & (df_fin["reports_count"] >= 2)]
    assert len(small_ngos) > 0

    # At least some small NGOs should achieve score >= 60
    small_scores = [assessments[nid]["trustability_score"] for nid in small_ngos["ngo_id"]]
    assert max(small_scores) >= 60.0, f"Small NGOs unfairly capped. Max: {max(small_scores)}"


def test_sanities_test5_missing_financial_reports(pipeline_data):
    """Sanity Test 5: Missing financial reports lowers coverage, but generates no fraud accusations."""
    df_fin = pipeline_data["fin_feats"]
    assessments = pipeline_data["assessments"]

    zero_rep_ngos = df_fin[df_fin["reports_count"] == 0]
    assert len(zero_rep_ngos) > 0, "No zero-report NGOs found"

    for nid in zero_rep_ngos["ngo_id"]:
        asmnt = assessments[nid]
        assert asmnt["dimension_scores"]["financial_transparency"] <= 20.0
        # Check missing evidence explicitly mentions lack of reports
        missing_str = " ".join(asmnt["missing_evidence"])
        assert "financial" in missing_str.lower() or "report" in missing_str.lower()
        # Verify no moral accusation in negative evidence
        for neg in asmnt["negative_evidence"]:
            assert "fraud" not in neg.lower()


def test_sanities_test6_anomaly_detection_behavior(pipeline_data):
    """Sanity Test 6: Statistically unusual financial pattern flagged by Isolation Forest without fraud claim."""
    df_fin = pipeline_data["fin_feats"]
    assessments = pipeline_data["assessments"]

    outliers = df_fin[df_fin["financial_anomaly_label"] == "Outlier"]
    assert len(outliers) > 0, "No outliers detected by Isolation Forest"

    for nid in outliers["ngo_id"][:3]:
        asmnt = assessments[nid]
        stat_str = " ".join(asmnt["statistical_findings"])
        assert "isolation forest" in stat_str.lower() or "unusual" in stat_str.lower()
        # Ensure limitations explicitly clarify anomaly != fraud
        lim_str = " ".join(asmnt["limitations"])
        assert "anomaly" in lim_str.lower()


def test_sanities_test7_accounting_inconsistency_handled(pipeline_data):
    """Sanity Test 7: Organization with deliberate accounting discrepancy on line items is flagged."""
    assessments = pipeline_data["assessments"]
    # We deliberately injected an error on NGO_00077 in generation
    if "NGO_00077" in assessments:
        asmnt = assessments["NGO_00077"]
        neg_str = " ".join(asmnt["negative_evidence"])
        assert "discrepancy" in neg_str.lower() or "reconciliation" in neg_str.lower()


def test_sanities_test9_no_public_projects(pipeline_data):
    """Sanity Test 9: No public projects lowers operational score without claiming projects never occurred."""
    df_op = pipeline_data["op_feats"]
    assessments = pipeline_data["assessments"]

    zero_prjs = df_op[df_op["total_projects_found"] == 0]
    assert len(zero_prjs) > 0, "No zero-project NGOs in sample"

    for nid in zero_prjs["ngo_id"]:
        asmnt = assessments[nid]
        assert asmnt["dimension_scores"]["operational_evidence"] <= 20.0
        missing_str = " ".join(asmnt["missing_evidence"])
        assert "project" in missing_str.lower()
        for neg in asmnt["negative_evidence"]:
            assert "fake" not in neg.lower()
            assert "non-existent" not in neg.lower()


def test_json_output_schema_conformity(pipeline_data):
    """Verifies that every generated NGO assessment contains all required Section 47 fields."""
    assessments = pipeline_data["assessments"]
    required_keys = [
        "ngo_id", "ngo_name", "assessment_date", "assessment_type",
        "trustability_score", "score_interpretation", "data_confidence",
        "confidence_band", "dimension_scores", "financial_analysis",
        "evidence_summary", "positive_evidence", "negative_evidence",
        "statistical_findings", "missing_evidence", "uncertainty",
        "limitations", "methodology"
    ]

    for nid, asmnt in list(assessments.items())[:20]:
        for k in required_keys:
            assert k in asmnt, f"Missing key '{k}' in assessment for {nid}"
        assert isinstance(asmnt["dimension_scores"], dict)
        assert len(asmnt["dimension_scores"]) == 4
        assert isinstance(asmnt["limitations"], list)
        assert len(asmnt["limitations"]) >= 3
