"""
Pydantic Schemas for Donations and Razorpay Payments
"""

from uuid import UUID
from datetime import datetime
from typing import Optional, List, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field, field_validator, ConfigDict


class DonationStatusEnum(str, Enum):
    INITIATED = "initiated"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    REFUNDED = "refunded"


class PaymentMethodEnum(str, Enum):
    UPI = "upi"
    CARD = "card"
    NETBANKING = "netbanking"
    CRYPTO = "crypto"


# -----------------------------------------------------------------------------
# Request Schemas
# -----------------------------------------------------------------------------

class DonationInitiateRequest(BaseModel):
    campaign_id: UUID = Field(..., description="Target campaign UUID")
    amount: float = Field(..., gt=0, description="Donation amount in INR (minimum ₹1.00)")
    donor_id: Optional[UUID] = Field(None, description="Donor User UUID (optional for guest donations)")
    payment_method: PaymentMethodEnum = Field(PaymentMethodEnum.UPI, description="Payment method: upi, card, netbanking, crypto")
    currency: str = Field("INR", max_length=3, description="Currency code (default INR)")
    donor_message: Optional[str] = Field(None, max_length=500, description="Optional public/private message from donor")
    is_anonymous: bool = Field(False, description="Whether to hide donor identity in public views")
    idempotency_key: Optional[str] = Field(None, max_length=100, description="Optional client-generated UUID to prevent duplicate orders on double click")

    @field_validator("amount")
    @classmethod
    def validate_min_amount(cls, v: float) -> float:
        if v < 1.0:
            raise ValueError("Minimum donation amount is ₹1.00 (100 paise)")
        return round(v, 2)


class DonationVerifyRequest(BaseModel):
    razorpay_order_id: str = Field(..., description="Order ID generated by Razorpay")
    razorpay_payment_id: str = Field(..., description="Payment ID received upon payment completion")
    razorpay_signature: str = Field(..., description="HMAC-SHA256 signature from Razorpay checkout")


# -----------------------------------------------------------------------------
# Response Schemas
# -----------------------------------------------------------------------------

class DonationInitiateResponse(BaseModel):
    donation_id: UUID = Field(..., description="Internal Eleos donation UUID")
    order_id: str = Field(..., description="Razorpay order ID to initialize checkout")
    razorpay_order_id: Optional[str] = Field(None, description="Alias for order_id for frontend SDKs")
    amount: float = Field(..., description="Amount in INR")
    amount_paise: int = Field(..., description="Amount in paise for Razorpay SDK")
    currency: str = Field("INR", description="Currency code")
    key_id: str = Field(..., description="Razorpay public Key ID")
    status: str = Field("initiated", description="Initial status of donation")


class DonationVerifyResponse(BaseModel):
    verified: bool = Field(..., description="Whether signature verification succeeded")
    donation_id: UUID = Field(..., description="Donation UUID")
    status: str = Field(..., description="Updated donation status")
    payment_id: str = Field(..., description="Razorpay payment ID")
    amount: Optional[float] = Field(None, description="Confirmed donation amount")
    message: str = Field(..., description="Status description")
    tax_receipt_token: Optional[str] = Field(None, description="80G Tax Exemption Receipt Token")
    blockchain_confirmed: bool = Field(True, description="Whether blockchain anchoring is confirmed")
    blockchain_tx_hash: Optional[str] = Field(None, description="Polygon transaction hash")
    polygon_tx_hash: Optional[str] = Field(None, description="Polygon transaction hash alias")


class DonationResponse(BaseModel):
    id: UUID
    donor_id: Optional[UUID] = None
    campaign_id: UUID
    amount: float
    currency: str
    payment_method: Optional[str] = None
    payment_gateway_order_id: Optional[str] = None
    payment_gateway_payment_id: Optional[str] = None
    status: str
    blockchain_tx_hash: Optional[str] = None
    blockchain_confirmed: Optional[bool] = False
    donor_message: Optional[str] = None
    is_anonymous: Optional[bool] = False
    campaign_title: Optional[str] = None
    ngo_name: Optional[str] = None
    created_at: datetime
    completed_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class DonationListResponse(BaseModel):
    total: int
    donations: List[DonationResponse]


# -----------------------------------------------------------------------------
# Webhook Schemas
# -----------------------------------------------------------------------------

class RazorpayPaymentEntity(BaseModel):
    id: str
    entity: str = "payment"
    amount: int
    currency: str = "INR"
    status: str
    order_id: Optional[str] = None
    method: Optional[str] = None
    description: Optional[str] = None
    notes: Optional[Dict[str, Any]] = None
    created_at: Optional[int] = None


class RazorpayPaymentPayload(BaseModel):
    payment: Dict[str, Any]


class RazorpayWebhookPayload(BaseModel):
    entity: str = "event"
    account_id: Optional[str] = None
    event: str  # e.g. 'payment.captured', 'payment.failed'
    contains: Optional[List[str]] = None
    payload: Dict[str, Any]
    created_at: Optional[int] = None
